name: ${pluginName}
version: ${version}
main: com.willfp.ecobosses.EcoBossesPlugin
api-version: 1.19

dependencies:
  - name: eco
    required: true
    bootstrap: false

  - name: libreforge
    required: false
    bootstrap: false

load-after:
  - name: eco
    bootstrap: false


permissions:
  ecobosses.*:
    description: All ecobosses permissions
    default: op
    children:
      ecobosses.command.*: true
  ecobosses.command.*:
    description: All ecobosses commands
    default: op
    children:
      ecobosses.command.ecobosses: true
      ecobosses.command.reload: true
      ecobosses.command.spawn: true
      ecobosses.command.give: true

  ecobosses.command.ecobosses:
    description: Allows the use of /ecobosses
    default: true

  ecobosses.command.give:
    description: Allows the use of /ecobosses give
    default: op

  ecobosses.command.spawn:
    description: Allows the use of /ecobosses spawn
    default: op

  ecobosses.command.killall:
    description: Allows the use of /ecobosses killall
    default: op

  ecobosses.command.reload:
    description: Allows the use of /ecobosses reload
    default: op
